name = "feed-the-moose"
compatibility_date = "2025-01-01"
main = ".svelte-kit/cloudflare/_worker.js"

[[routes]]
pattern = "bubbas.food"
custom_domain = true

[assets]
directory = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "feed-the-moose-db"
database_id = "344c5826-8a70-4a9f-abc2-6794523bd0b7"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "moose-photos"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
