name = "feed-the-moose-cron"
main = "worker.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["* * * * *"]

[vars]
APP_URL = "https://feed-the-moose.rupertcarr.workers.dev"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
